name: padiham
favicon: null
layout_spectrum: 0.75044
typography_spectrum: 0.56927
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#94e690'
    - '#fffe09'
    - '#f6a706'
    - '#2ba839'
    - '#c53a05'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.6812330244574696
  rhythmicContrast: 0.25
purpose: []
